### ISSUE TITLE
Start new forum thread (update the one in the README) 

### ISSUE THREAD

**Issue by luzpaz** [mdkus/PieMenu#2]
Thanks @mdkus for stepping up and becoming the maintainer of PieMenu. Would you mind opening a new forum thread announcing this and that also functions as a thread for discussion/feeback/bug reporting etc... ? The [discussion](https://github.com/mdkus/PieMenu#discussion) link in the README will also need to be updated when you do). TIA!

**Comment by mdkus** [comment]
Yes, I'll open a new forum thread and commit an update to the README. Thank you!

**Comment by mdkus** [comment]
I registrated an account 'mdkus' in FreeCAD forum, but it couldn't be activated until now. Trying to contact a board admin failed. What could I've made wrong?

**Comment by luzpaz** [comment]
I think the forum registration is broken. This is not the first i've heard of this

**Comment by mdkus** [comment]
Thanks for the info. I will try it from time to time. When my account is activated, I'll start a new forum thread.

**Comment by luzpaz** [comment]
Seems yorik fiddled with DNS settings and b0rked something. It's getting addressed.

**Comment by mdkus** [comment]
Hi luzpaz,
opened two new issues with the same title as in triplus' rep, where this two issues can be closed. I suggest the same procedure for the other issues, when vetted.

**Comment by mdkus** [comment]
Just committed the update of README with an actual link to the [new forum thread](https://forum.freecadweb.org/viewtopic.php?f=34&t=72205) I've started.

**Comment by luzpaz** [comment]
Sweet!
