### ISSUE TITLE
Choosing Arch toolbar in preferences loads all the icons in to piemenu and overloads the UI

### ISSUE THREAD

**Issue by mdkus** [mdkus/PieMenu#5]
**@luzpaz** Yes, that's right. The actual code loads all available commands of a toolbar menu, even when overloading the UI. What should be the right behaviour if there a many commands available? Any suggestions?

**Comment by luzpaz** [comment]
How does realthunder's branch tackle this?

**Comment by mdkus** [comment]
I think realthunder's branch avoids the problem: toolbar pie menus there are not automatically generated. You have to add every toolbar command by hand. I suggest to make the automatically added tool bar commands deletable in some way and optional persistent as 'normal' self-created pie menus, if wanted so.

**Comment by luzpaz** [comment]
Makes sense. Sounds like a lot of coding, but that customization would be preferable. What do you think?

**Comment by mdkus** [comment]
I think this is not as complicated as it seems at first sight. I'll do some first tests next time.

**Comment by mdkus** [comment]
@luzpaz Ok, I implemented that in the new version 1.2. A tutorial can be found [here](https://www.youtube.com/watch?v=1uyg-2U5wfE).

**Comment by luzpaz** [comment]
Feel free to close this ticket when necessary
