### ISSUE TITLE
[PieMenu] Create an SVG icon for this addon

### ISSUE THREAD

**Issue by mdkus** [mdkus/PieMenu#6]
@luzpaz @pgilfernandez

Replaced my quickly created pie menu logo with the user suggested logo, which looks better. I hope that I can make @pgilfernandez happy with it. Before replacing I have removed all inkscape entries.

**Comment by luzpaz** [comment]
git commit ?

**Comment by pgilfernandez** [comment]
It's fine to me =D

**Comment by mdkus** [comment]
Yes, I [committed](https://github.com/mdkus/PieMenu/commit/f7d54e47bca0b5d7c1c1725b4068de429c879efc) the change of the logo.

**Comment by luzpaz** [comment]
Great! Please close ticket.
