### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by MisterMakerNL** [mdkus/PieMenu#7]
I got asked to check if my Dark theme need adjusting for the Piemenu, but it seems to work just fine.
Although I see 2 small UI bugs:
![afbeelding](https://user-images.githubusercontent.com/29804962/193656176-5bb6ccbc-fc72-4d4f-8106-3f81fde1b14b.png)
Edit2:
a third is the arrows they cut in the text:
![afbeelding](https://user-images.githubusercontent.com/29804962/193656569-7a8a9f18-cadd-473a-b5d4-1c4aa5cf6215.png)

Edit:
btw Super awesome you are picking this project up!

**Comment by mdkus** [comment]
Thank you for your tests. I'll try to reproduce this.

**Comment by mdkus** [comment]
Ok, the first two bugs are reproducible for me (Windows 11):
![ExtremeProDark_1](https://user-images.githubusercontent.com/4068805/193676165-a29694f3-4d55-4869-9b38-778e11f23975.png)

The third not:
![ExtremeProDark_2](https://user-images.githubusercontent.com/4068805/193673154-042309ff-314f-4bd8-9619-98b65a1ef31e.png)
Is there any option to enlarge menu texts in FreeCAD? I haven't found it yet...

**Comment by MisterMakerNL** [comment]
Aha I see the last bug was only in 0.21, when I checked it in 0.20.1 it works!

Below version stats, might already been fixed, I don't think I am running the latest 0.21.
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.30345 (Git)
Build type: Release
Branch: master
Hash: f42a47aa0fd8c4f34ef63c185d9f29b9b6e84737
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
  * Assembly3 0.11.3
  * Behave-Dark-Colors 0.1.1
  * BIM 2021.12.0 (Disabled)
  * Dracula 0.0.2
  * ExtremeProDark 2.2.0
  * FeedsAndSpeeds 0.4.0
  * FEM_FrontISTR 0.1.0
  * IconThemes
  * lattice2 1.0.0
  * PieMenu 1.1.6
  * PieMenu.backup1664822562.2342157
  * ProDarkThemePreferencePack 1.0.0
  * SelectorToolbar
  * sheetmetal 0.2.57
  * SP_Startup
  * ToolbarStyle
[/code]

**Comment by mdkus** [comment]
Thanks for the info! Where can I find 0.21? Is that the actual FC master?

**Comment by MisterMakerNL** [comment]
https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by MisterMakerNL** [comment]
I noticed the blue bar on another tab bar, and realize it is an error in my theme so I dove into it and fixed it a bit:
![afbeelding](https://user-images.githubusercontent.com/29804962/193892601-4900c38c-3324-466c-be97-5566981e6f1b.png)

**Comment by mdkus** [comment]
In 0.20.1 you also fixed the second bug. In 0.21 it works too.
![ExtremeProDark_3](https://user-images.githubusercontent.com/4068805/194154829-b7380b49-62cb-409f-b2cb-60a793608ecc.png)
Only the third bug remains for 0.21, but not in 0.20.1:
![ExtremeProDark_4](https://user-images.githubusercontent.com/4068805/194162541-f8935b9a-ac41-4d70-bcc3-dcf52bc50edf.png)

**Comment by mdkus** [comment]
@MisterMakerNL The new update of pie menu (1.1.12) should fix the third bug. Please check out. Tested with v0.21 Python 3.10:

![ExtremeProDark_5](https://user-images.githubusercontent.com/4068805/200108429-c72a92cb-64b4-4972-9d63-6e6662c631d2.png)

But one problem still remains: In dark mode all checkable items are shown checked although they aren't.

![ExtremeProDark_6](https://user-images.githubusercontent.com/4068805/200109339-56b22cf8-b38d-4da5-9880-69cb10304142.png)
![ExtremeProDark_7](https://user-images.githubusercontent.com/4068805/200109232-e113da52-330d-42c0-9b43-118ffd515114.png)

Any idea?

**Comment by MisterMakerNL** [comment]
Edit:
One icon is missing the unchecked check mark light.
Other things where links to icons in my theme!
So I fixed the biggest issue in the ExtremeProDark, it's not perfect yet.
It also needs to be pushed to main, as all dark theme's are missing this icons.
https://github.com/MisterMakerNL/ExtremeProDark/commit/117147dd738f9449d51ff7fef4668ffc1b79c04f
![freecad_8hMYstDyyL](https://user-images.githubusercontent.com/29804962/202913238-cea476d0-3f80-44dd-88d4-b4d8a9485c42.gif)

**Comment by mdkus** [comment]
@MisterMakerNL
Good collab. Can we close this issue?

**Comment by MisterMakerNL** [comment]
Yeah, looks good!
